version: '3.7'
services:
  adminpostgres:
    image: postgres:14
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
        - admin_postgres_data:/var/lib/postgresql/data
    networks:
        - internal

  cicd_delegator:
    env_file: .env
    build: ./cicd_delegator
    networks:
        - internal
        - cicd_delegator
    environment:
        INDEX_HOST: http://${CICD_NETWORK_NAME}_adminodoo_proxy:80
    restart: "unless-stopped"
    volumes:
        - ./cicd_delegator/app:/usr/src/app

  logs:
    build:
      context:
        logs
      args:
        LOGIO_RELATIVE_PATH: '/logs'
    environment:
      TIMEZONE: Europe/Berlin
    expose:
        - 6689
    networks:
      - internal
    volumes:
      - rolling_log:/rolling
    privileged: true

        
  cicd_postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: 'unless-stopped'
    command: postgres -c 'max_connections=1000'
    shm_size: 1G
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
    volumes:
        - cicd_postgres_data:/var/lib/postgresql/data
        - /tmp/dump:/tmp/dump
    ports:
        - "${DB_HOST}:${DB_PORT}:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 3s
        timeout: 5s
        retries: 5

  nginx:
    build: nginx
    restart: unless-stopped
    networks:
        - cicd_delegator
        - internal
    environment:
      PROXY_PASS_INDEX: "${CICD_NETWORK_NAME}adminodoo_proxy:80"
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    ports:
        - ${CICD_BINDING}:80

  webssh:
    build: webssh
    restart: unless-stopped
    networks:
      - cicd_delegator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/odoo:/opt/odoo
      - ${ODOO_SETTINGS}:/root/.odoo
      - ${CICD_WORKSPACE}:/cicd_workspace

    
volumes:
    admin_postgres_data:
    cicd_postgres_data:
    rolling_log:
    uploaded_dumps:
    log_history:
networks:
    cicd_delegator:
        name: ${CICD_NETWORK_NAME}
    internal:
        name: "${CICD_NETWORK_NAME}_internal"
