version: '3.7'
services:
  jenkins:
    restart: 'unless-stopped'
    image: 'docker.io/bitnami/jenkins:2-debian-10'
    ports:
        - '8080:8080'
        #- '10.10.173.111:50000:50000'
    volumes:
      - ./data:/bitnami/jenkins'
    deploy:
      resources:
        limits:
          memory: 1024M